eureka:
  client:
    serviceUrl:
# Single Server
#      defaultZone: http://localhost:8010/eureka/
# Cluster Servers
       defaultZone: http://eureka-primary:8016/eureka/,http://eureka-secondary:8017/eureka/,http://eureka-tertiary:8018/eureka/
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

